# Generated by Django 4.0.2 on 2022-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('ground_flour', models.ImageField(upload_to='map_output/')),
                ('first_flour', models.ImageField(upload_to='map_output/')),
                ('second_flour', models.ImageField(upload_to='map_output/')),
            ],
        ),
    ]
